#
#  .swiftlint.yml
#  Netomi
#
#  Created by Vishal  on 26/03/25.


disabled_rules:
- trailing_whitespace
- non_optional_string_data_conversion
- inclusive_language
- identifier_name
- force_cast

opt_in_rules:
- trailing_whitespace
- closure_parameter_position

excluded:
- Carthage
- Pods
- .build
- Generated

line_length:
    warning: 350
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 1600
    error: 1800
file_length:
    warning: 1800
    error: 2000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 40
    error: 50
type_name:
  max_length: 70

reporter: "xcode"
