name: Validate SDK PR

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'NetomiChatSDK.podspec'
      - 'Package.swift'

jobs:
  validate:
    name: Lint and Build SDK
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Validate Podspec
        run: pod spec lint NetomiChatSDK.podspec --allow-warnings --verbose

      - name: Validate Swift Package Syntax
        run: |
          echo "Validating Package.swift syntax..."
          swift package dump-package > /dev/null

      - name: Resolve Swift Package Dependencies
        run: |
          echo "Resolving Swift Package dependencies and verifying checksums..."
          swift package resolve

      - name: Confirm Binary Target Unpacks
        run: echo "✅ Binary target zip resolved and checksum verified. No build required for binary-only SDK."
